DefaultContentLanguage = "en"
Paginate = 10
SectionPagesMenu = "main"
baseURL = "https://niagara2022stories.ca/"
enableRobotsTXT = true
googleAnalytics = ""
languageCode = "en-us"
theme = "ananke"
title = "Niagara 2022 Stories"
[languages.en]
contentDir = "content/"
title = "Niagara2022stories"
weight = 1
[params]
background_color_class = "bg-black"
custom_css = ["css/custom.css"]
description = "Collecting Niagara 2022 Canada Games stories"
facebook = ""
favicon = ""
github = "https://github.com/jyounker/niagara2022stories"
gitlab = ""
instagram = "https://instagram.com/niagara2022stories"
linkedin = ""
mastodon = ""
recent_posts_number = 5
rss = ""
site_logo = ""
slack = ""
stackoverflow = ""
twitter = "https://twitter.com/niagara2022stories"
youtube = ""
[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5
